CREATE TABLE topicos(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    mensaje TEXT,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('ABIERTO', 'RESUELTO', 'CERRADO') NOT NULL,
    author_id BIGINT,
    curso VARCHAR(255) NOT NULL
    );